schema_version = "1.0.0"

id = "simple_collider"
version = "1.0.0"
name = "Simple Collider"
tagline = "create physics colliders for games and real-time applications"
maintainer = "Matthias Patscheider <patscheider.matthias@gmail.com>"
type = "add-on"

website = "https://weisl.github.io/collider_overview/"

tags = ["3D View", "Scene", "User Interface"]

blender_version_min = "4.2.0"

license = [
    "SPDX:GPL-3.0-or-later",
]

platforms = ["windows-x64", "linux-x64"]

wheels = [
    "./wheels/coacd-1.0.5-cp36-abi3-win_amd64.whl",
    "./wheels/numpy-2.2.1-cp311-cp311-win_amd64.whl",
]

copyright = [
    "2023 Matthias Patscheider",
]

[permissions]
files = ".py preset files, AutoConvex exe, export files"

[build]
paths_exclude_pattern = [
    "__pycache__/",
    "/.git/",
    "/*.zip",
]
